### ISSUE TITLE
Add support for PSR3 LoggerInterface to ease debugging

### ISSUE THREAD

**Issue by GijsL** [voucherifyio/voucherify-php-sdk#44]
Hi,

Would it be possible to add a logger feature to be able to see the curl requests/responses. This will be very helpful during implementation and testing.
You could make it optional and very generic with the PSR3 LoggerInterface.

**Comment by mandraszyk** [comment]
Hi,
Sure, we can add logger future. We will release new version early next week.

**Comment by mandraszyk** [comment]
Version 1.6.0 released. VoucherifyClient now has `setLogger()` method which can be used to pass own logger and preview curl response / requests data.
