### ISSUE TITLE
Pass timeout value to Create and Validate methods.

### ISSUE THREAD

**Issue by twilsman** [voucherifyio/voucherify-php-sdk#51]
We would like the ability to pass a timeout value to the create and validate methods.

We use these as part our checkout process, and we'd like the option to be pretty aggressive with a timeout to prevent the experience from hanging.

Thanks!

**Comment by mandraszyk** [comment]
Hi, We can prepare additional function i.e. setConnectionOptions($options) in VoucherifyClient so you will be able to pass additional curl settings like timeout globally for each request - is this approach ok with your case ?

**Comment by twilsman** [comment]
Hello!  Sorry for the late response.  Yes, I believe this would solve our problem.  Thank you!

**Comment by mandraszyk** [comment]
Hi, Cool - i will this feature before end of this week.

**Comment by mandraszyk** [comment]
New 1.7.1 version brings `setConnectionOptions` method to VoucherifyClient - i hope it will help you resolve your problems.
