### ISSUE TITLE
Implement customers getList() method

### ISSUE THREAD

**Issue by lroot** [voucherifyio/voucherify-php-sdk#55]
The API supports listing and paging of customers (https://docs.voucherify.io/reference#list-customers). However the current customers object is lacking a getList() method. Please consider adding this method, just like it exists for the vouchers object (https://github.com/voucherifyio/voucherify-php-sdk/blob/master/src/Vouchers.php#L97)

**Comment by mandraszyk** [comment]
Hi. Sure, we will add this. Expect new release during this weekend ;)

**Comment by mandraszyk** [comment]
Released in v1.7.4
