### ISSUE TITLE
Please add support for forced product deletion

### ISSUE THREAD

**Issue by lroot** [voucherifyio/voucherify-php-sdk#60]
The core REST API supports a param that allows for a Product to be fully deleted such that the source_id can be reused: https://docs.voucherify.io/reference?utm_source=github&utm_medium=sdk&utm_campaign=acq#delete-product

Currently the Product delete method does not support this flag: https://github.com/voucherifyio/voucherify-php-sdk/blob/master/src/Products.php#L86

Please consider adding this param to match the current REST API.

**Comment by mandraszyk** [comment]
Hi, sure. I will release new version during this weekend.

**Comment by mandraszyk** [comment]
Hello, Please check newest release - v1.7.8

**Comment by lroot** [comment]
Thanks!
