### ISSUE TITLE
Voucherify list code only and store into Mysql

### ISSUE THREAD

**Issue by musicophile** [voucherifyio/voucherify-php-sdk#63]
How can i list vouchers code only from vouchers list and store them in MySQL database please help me on this? Thank you.

**Comment by mandraszyk** [comment]
Hi, To get vouchers list you can use `$client->vouchers->getList($params)` method. To iterate through the total number of vouchers you will have to increase `page` param value before calling getList in a loop. Then check response `total` value against a local counter, to see if you've reached the end. Getting the code from the response and storing it in MySQL should be easy!

**Comment by musicophile** [comment]
Thank You Mr Through this function $client->vouchers->getList($params) i can list all vouchers and their information but if i want to list only code of vouchers without their date, redemption, expire date and othe information. Please help me on this. Thank you In advance.
