### ISSUE TITLE
Provide useful example in the documentation

### ISSUE THREAD

**Issue by federicogatti** [voucherifyio/voucherify-php-sdk#74]
The SDK documentation is totally useless, it doesn't provide any example in order to understand how to use it. For example, how can I understand how to do  the **POST** request `/vouchers/{code}/redemption` with body
```json
{
  "order": {
    "amount": 10000
  }
}
```
using this docs https://github.com/voucherifyio/voucherify-php-sdk#redeem-voucher ? You are listing only the API interface of the class with any other indication.

Also, the tests folder doesn't contain any unit tests, only integration tests.

Can you add in the documentation useful examples?

**Comment by mandraszyk** [comment]
Hello, 

You can find the specification of **redeem** endpoint here: [Voucherify API Docs](https://docs.voucherify.io/reference?utm_source=github&utm_medium=sdk&utm_campaign=acq#redeem-voucher)

An example (copied from provided test file):
```
$client->redemptions->redeem("test-code", (object)[
    "customer" => (object)[
         "id" => "test-customer-id"
     ]
]);
```
can be easily adjusted to your needs and is perfectly covered by the method description:
```
$client->redemptions->redeem($code, $params);
```
No additional tests are going to be provided, except those covering new methods or new modules.

Best regards!
